redis:
  closeClient: true
  config: &redis-config
    port: 6379
    host: '101.34.66.96'
    password: 'AhGHNXBFFNKJ'
database:
  type: 'postgres'
  host: '101.34.66.96'
  port: 5432
  username: 'nest_shop'
  password: 'AhGHNXBFFNKJ'
  database: 'nestshop'
  synchronize: false
  logging:
    - error
    - log
    - info
    - query
    - warn
  maxQueryExecutionTime: -1
  entities:
    - '../../node_modules/@adachi-sakura/nest-shop-entity/dist/**/*.js'
  cache:
    type: 'ioredis'
    options: *redis-config
server:
  port: 4000
  prefix: '/api'
  allowReferer: 'zy.ci'
  allowOrigins:
    - "https://zy.ci"
    - "https://admin.zy.ci"
  rootAccount:
    email: 'admin@zy.ci'
    nickname: admin
  session:
    secret: 'my-secret'
    resave: false
    saveUninitialized: false
  validator:
    whitelist: true
    transform: true
graphql:
  debug: true
  playground: true
  autoSchemaFile: true
  installSubscriptionHandlers: true
  useGlobalPrefix: true
  path: '/graphql'
swagger:
  prefix: '/doc'
jwt:
  secret: 'nest_shop_jwt_secret'
  signOptions:
    expiresIn: '7200s'
elasticsearch:
  node:
    - 'http://elasticsearch:9200'

